#!/bin/sh

# Set these paths appropriately

BIN=/Users/lorrie/Documents/M1/TER/TreeTagger/bin
CMD=/Users/lorrie/Documents/M1/TER/TreeTagger/cmd
LIB=/Users/lorrie/Documents/M1/TER/TreeTagger/lib

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/tokenize.pl
ABBR_LIST=${LIB}/swahili-abbreviations
PARFILE=${LIB}/swahili.par

$TOKENIZER -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
